export const programmingLanguages = [
  { name: 'Pascal', value: 'Pascal' },
  { name: 'JavaScript', value: 'JavaScript' },
  { name: 'TypeScript', value: 'TypeScript' },
  { name: 'Python', value: 'Python' },
  { name: 'TSX', value: 'TSX' },
  { name: 'JSX', value: 'JSX' },
  { name: 'Vue', value: 'Vue' },
  { name: 'Go', value: 'Go' },
  { name: 'C', value: 'C' },
  { name: 'C++', value: 'C++' },
  { name: 'Java', value: 'Java' },
  { name: 'C#', value: 'C#' },
  { name: 'Visual Basic .NET', value: 'Visual Basic .NET' },
  { name: 'SQL', value: 'SQL' },
  { name: 'Assembly Language', value: 'Assembly Language' },
  { name: 'PHP', value: 'PHP' },
  { name: 'Ruby', value: 'Ruby' },
  { name: 'Swift', value: 'Swift' },
  { name: 'SwiftUI', value: 'SwiftUI' },
  { name: 'Kotlin', value: 'Kotlin' },
  { name: 'R', value: 'R' },
  { name: 'Objective-C', value: 'Objective-C' },
  { name: 'Perl', value: 'Perl' },
  { name: 'SAS', value: 'SAS' },
  { name: 'Scala', value: 'Scala' },
  { name: 'Dart', value: 'Dart' },
  { name: 'Rust', value: 'Rust' },
  { name: 'Haskell', value: 'Haskell' },
  { name: 'Lua', value: 'Lua' },
  { name: 'Groovy', value: 'Groovy' },
  { name: 'Elixir', value: 'Elixir' },
  { name: 'Clojure', value: 'Clojure' },
  { name: 'Lisp', value: 'Lisp' },
  { name: 'Julia', value: 'Julia' },
  { name: 'Matlab', value: 'Matlab' },
  { name: 'Fortran', value: 'Fortran' },
  { name: 'COBOL', value: 'COBOL' },
  { name: 'Bash', value: 'Bash' },
  { name: 'Powershell', value: 'Powershell' },
  { name: 'PL/SQL', value: 'PL/SQL' },
  { name: 'CSS', value: 'CSS' },
  { name: 'Racket', value: 'Racket' },
  { name: 'HTML', value: 'HTML' },
  { name: 'NoSQL', value: 'NoSQL' },
  { name: 'Natural Language', value: 'Natural Language' },
  { name: 'CoffeeScript', value: 'CoffeeScript' },
];
